In [1]:
# Import NumPy
import numpy as np

In [3]:
# Create a numpy array with np.array([Any List or Sequence data])
test_array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print test_array

[ 1.  2.  3.  4.  5.]


In [6]:
# The array has attributes that can be accessed
# shape (tuple indicating the dimensions)
print test_array.shape
# Rank 
print len(test_array.shape)
test_array.ndim

(5,)
1


1

In [7]:
# nested sequence to create multi dimensional array
two_dim_test_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [8]:
two_dim_test_array.shape

(2, 5)

In [9]:
two_dim_test_array.ndim

2

In [11]:
# print test_array for reference
print test_array

[ 1.  2.  3.  4.  5.]


In [12]:
# data type 
print test_array.dtype

float64


In [13]:
# data type can also be specifed at creation time
test_array_128 = np.array(test_array, dtype='float128')

In [10]:
# data type 
print test_array_128.dtype

float128


In [11]:
# np.arange(start, stop, step_size)
# Like range() for python lists/arrays
test_array = np.arange(1.0, 105.82, 2.3184)
print test_array


# np arrays can be reshaped using same number of elements
# Shape = (46,), Rank = 1
test_array.shape
print len(test_array.shape)

[  1.       3.3184   5.6368   7.9552  10.2736  12.592   14.9104  17.2288
  19.5472  21.8656  24.184   26.5024  28.8208  31.1392  33.4576  35.776
  38.0944  40.4128  42.7312  45.0496  47.368   49.6864  52.0048  54.3232
  56.6416  58.96    61.2784  63.5968  65.9152  68.2336  70.552   72.8704
  75.1888  77.5072  79.8256  82.144   84.4624  86.7808  89.0992  91.4176
  93.736   96.0544  98.3728 100.6912 103.0096 105.328 ]
1


In [12]:
# np.array.reshape (23,2)  Returns a reshaped array
print test_array.reshape(23,2)
# Shape = (46,), Rank = 1
test_array.shape
print len(test_array.shape)

[[  1.       3.3184]
 [  5.6368   7.9552]
 [ 10.2736  12.592 ]
 [ 14.9104  17.2288]
 [ 19.5472  21.8656]
 [ 24.184   26.5024]
 [ 28.8208  31.1392]
 [ 33.4576  35.776 ]
 [ 38.0944  40.4128]
 [ 42.7312  45.0496]
 [ 47.368   49.6864]
 [ 52.0048  54.3232]
 [ 56.6416  58.96  ]
 [ 61.2784  63.5968]
 [ 65.9152  68.2336]
 [ 70.552   72.8704]
 [ 75.1888  77.5072]
 [ 79.8256  82.144 ]
 [ 84.4624  86.7808]
 [ 89.0992  91.4176]
 [ 93.736   96.0544]
 [ 98.3728 100.6912]
 [103.0096 105.328 ]]
1


In [13]:
# reshape() function itself does not modify original
test_array = test_array.reshape(23,2)

In [14]:
# Shape = (23,2), Rank = 2
test_array.shape
print len(test_array.shape)

2


In [15]:
# nested sequence to create multi dimensional array                                                                                                         
# 4x7 2-D array
one_d_array=np.array([1,2,3,4,5,6,7])
test_array = np.array([one_d_array, one_d_array*3, one_d_array*5, one_d_array*7])

In [16]:
# Print Test array 4x7
print test_array

[[ 1  2  3  4  5  6  7]
 [ 3  6  9 12 15 18 21]
 [ 5 10 15 20 25 30 35]
 [ 7 14 21 28 35 42 49]]


In [17]:
# Shape
print test_array.shape

(4, 7)


In [18]:
# Rank
print test_array.ndim

2


In [19]:
# Slice along the first dimension
print test_array[2]

[ 5 10 15 20 25 30 35]


In [20]:
# Slince along the first dimension with index range
# test_array[start_index:stop_index]
# This gives corresponding elements from [start,stop)
print test_array[1:3]

[[ 3  6  9 12 15 18 21]
 [ 5 10 15 20 25 30 35]]


In [21]:
# Elements accessed by index along each dimension
print test_array[2,5]

30


In [22]:
# Slice across two dimensions
print test_array[1:3, 2:5]

[[ 9 12 15]
 [15 20 25]]


In [23]:
# Transpose an array with T operator
print test_array.T

[[ 1  3  5  7]
 [ 2  6 10 14]
 [ 3  9 15 21]
 [ 4 12 20 28]
 [ 5 15 25 35]
 [ 6 18 30 42]
 [ 7 21 35 49]]
